#line 2 "qasm-scanner.c"

#line 4 "qasm-scanner.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer qasm_create_buffer
#define yy_delete_buffer qasm_delete_buffer
#define yy_flex_debug qasm_flex_debug
#define yy_init_buffer qasm_init_buffer
#define yy_flush_buffer qasm_flush_buffer
#define yy_load_buffer_state qasm_load_buffer_state
#define yy_switch_to_buffer qasm_switch_to_buffer
#define yyin qasmin
#define yyleng qasmleng
#define yylex qasmlex
#define yylineno qasmlineno
#define yyout qasmout
#define yyrestart qasmrestart
#define yytext qasmtext
#define yywrap qasmwrap
#define yyalloc qasmalloc
#define yyrealloc qasmrealloc
#define yyfree qasmfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 34
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE qasmrestart(qasmin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int qasmleng;

extern FILE *qasmin, *qasmout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE qasmlex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-qasmlineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < qasmleng; ++yyl )\
                    if ( qasmtext[yyl] == '\n' )\
                        --qasmlineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up qasmtext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up qasmtext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 * Given that the standard has decreed that size_t exists since 1989,
 * I guess we can afford to depend on it. Manoj.
 */

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via qasmrestart()), so that the user can continue scanning by
	 * just pointing qasmin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when qasmtext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int qasmleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow qasmwrap()'s to do buffer switches
 * instead of setting up a fresh qasmin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void qasmrestart (FILE *input_file  );
void qasm_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE qasm_create_buffer (FILE *file,int size  );
void qasm_delete_buffer (YY_BUFFER_STATE b  );
void qasm_flush_buffer (YY_BUFFER_STATE b  );
void qasmpush_buffer_state (YY_BUFFER_STATE new_buffer  );
void qasmpop_buffer_state (void );

static void qasmensure_buffer_stack (void );
static void qasm_load_buffer_state (void );
static void qasm_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER qasm_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE qasm_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE qasm_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE qasm_scan_bytes (yyconst char *bytes,int len  );

void *qasmalloc (yy_size_t  );
void *qasmrealloc (void *,yy_size_t  );
void qasmfree (void *  );

#define yy_new_buffer qasm_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        qasmensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            qasm_create_buffer(qasmin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        qasmensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            qasm_create_buffer(qasmin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *qasmin = (FILE *) 0, *qasmout = (FILE *) 0;

typedef int yy_state_type;

extern int qasmlineno;

int qasmlineno = 1;

extern char *qasmtext;
#define yytext_ptr qasmtext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up qasmtext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	qasmleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 39
#define YY_END_OF_BUFFER 40
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_acclist[276] =
    {   0,
       32,   32,   40,   38,   39,   34,   38,   39,   37,   39,
       31,   38,   39,   35,   38,   39,   38,   39,   28,   38,
       39,   36,   38,   39,   30,   38,   39,   30,   38,   39,
       30,   38,   39,   30,   38,   39,   30,   38,   39,   30,
       38,   39,   30,   38,   39,   30,   38,   39,   30,   38,
       39,   30,   38,   39,   30,   38,   39,   30,   38,   39,
       30,   38,   39,   30,   38,   39,   30,   38,   39,   38,
       39,   30,   38,   39,   30,   38,   39,   30,   38,   39,
       30,   38,   39,   30,   38,   39,   30,   38,   39,   30,
       38,   39,   30,   38,   39,   30,   38,   39,   30,   38,

       39,   30,   38,   39,   30,   38,   39,   30,   38,   39,
       30,   38,   39,   30,   38,   39,   32,   39,   33,   39,
       34,   35,   29,   28,   36,   30,   30,   30,   30,   30,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       30,   30,   30,   30,   30,   27,   30,   30,   30,   30,
       26,   30,   30,    1,   30,   30,   30,   30,   30,   30,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       30,   30,   30,   27,   30,   30,   30,   30,   26,   30,
       32,   29,    5,   30,   23,   30,   22,   30,   24,   30,
        8,   30,   10,   30,   11,   30,   16,   30,   15,   30,

        7,   30,   19,   30,   21,   30,   20,   30,   14,   30,
       13,   30,    9,   30,   12,   30,    3,   30,   18,   30,
       17,   30,   25,   30,    4,   30,    6,   30,    5,   30,
       23,   30,   22,   30,   24,   30,    8,   30,   10,   30,
       11,   30,   16,   30,   15,   30,    7,   30,   19,   30,
       21,   30,   20,   30,   14,   30,   13,   30,    9,   30,
       12,   30,    3,   30,   18,   30,   17,   30,   25,   30,
        4,   30,    6,   30,    2
    } ;

static yyconst flex_int16_t yy_accept[166] =
    {   0,
        1,    1,    1,    2,    3,    4,    6,    9,   11,   14,
       17,   19,   22,   25,   28,   31,   34,   37,   40,   43,
       46,   49,   52,   55,   58,   61,   64,   67,   70,   72,
       75,   78,   81,   84,   87,   90,   93,   96,   99,  102,
      105,  108,  111,  114,  117,  119,  121,  122,  123,  124,
      125,  126,  127,  128,  129,  130,  131,  132,  133,  134,
      135,  136,  137,  138,  139,  140,  141,  142,  143,  144,
      145,  146,  148,  149,  150,  151,  153,  153,  154,  155,
      156,  157,  158,  159,  160,  161,  162,  163,  164,  165,
      166,  167,  168,  169,  170,  171,  172,  173,  174,  176,

      177,  178,  179,  181,  182,  183,  185,  187,  189,  191,
      193,  195,  197,  199,  201,  203,  205,  207,  209,  211,
      213,  215,  217,  219,  221,  223,  225,  227,  229,  229,
      231,  233,  235,  237,  239,  241,  243,  245,  247,  249,
      251,  253,  255,  257,  259,  261,  263,  265,  267,  269,
      271,  273,  275,  275,  275,  275,  275,  275,  275,  275,
      275,  275,  275,  276,  276
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    5,    6,    1,    1,    7,    1,    1,
        1,    1,    1,    1,    8,    9,    1,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   11,   12,    1,
        1,    1,    1,    1,   13,   14,   15,   16,   17,   18,
       19,   20,   21,   22,   18,   23,   24,   25,   26,   27,
       28,   29,   30,   31,   32,   33,   18,   34,   18,   35,
        1,    1,    1,    1,    8,    1,   36,   37,   38,   39,

       40,   18,   41,   42,   43,   44,   18,   45,   46,   47,
       48,   49,   50,   51,   52,   53,   54,   55,   18,   56,
       18,   57,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[58] =
    {   0,
        1,    1,    2,    1,    3,    1,    1,    4,    1,    4,
        5,    1,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6
    } ;

static yyconst flex_int16_t yy_base[174] =
    {   0,
        0,   57,  424,  423,  427,  430,  113,  430,  430,    0,
        0,  416,    0,  100,    0,   95,  103,   91,  104,  100,
      102,  119,   98,  116,  128,  121,  131,  415,  132,  144,
      413,  154,  157,  158,  162,  170,  179,  181,  155,  190,
      194,  212,  200,  160,    0,  430,  130,    0,    0,  413,
        0,    0,  175,  157,  210,  181,  180,  186,  199,  216,
      222,  212,  206,  208,  217,  227,  225,  222,  224,  229,
      237,  412,  228,  236,  250,  411,  243,  409,  430,  260,
      263,  266,  271,  264,  269,  274,  272,  280,  277,  282,
      285,  287,  292,  302,  299,  294,  317,  318,  296,  319,

      320,  321,  330,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,  318,  408,
      407,  406,  405,  404,  403,  399,  398,  395,  390,  383,
      377,  371,  362,  360,  358,  354,  353,  352,  346,  297,
      183,  171,  322,  316,  320,  334,  135,  350,    0,  123,
      351,  359,  430,  430,  374,  380,  116,  386,  389,  392,
      398,  401,  407
    } ;

static yyconst flex_int16_t yy_def[174] =
    {   0,
      164,  164,  165,  165,  164,  164,  164,  164,  164,  166,
      167,  164,  168,  169,  169,  169,  169,  169,  169,  169,
      169,  169,  169,  169,  169,  169,  169,  169,  164,  170,
      170,  170,  170,  170,  170,  170,  170,  170,  170,  170,
      170,  170,  170,  170,  171,  164,  164,  166,  172,  164,
      168,  169,  169,  169,  169,  169,  169,  169,  169,  169,
      169,  169,  169,  169,  169,  169,  169,  169,  169,  169,
      169,  169,  169,  169,  169,  169,  164,  170,  164,  170,
      170,  170,  170,  170,  170,  170,  170,  170,  170,  170,
      170,  170,  170,  170,  170,  170,  170,  170,  170,  170,

      170,  170,  170,  171,  172,  169,  169,  169,  169,  169,
      169,  169,  169,  169,  169,  169,  169,  169,  169,  169,
      169,  169,  169,  169,  169,  169,  169,  169,  164,  170,
      170,  170,  170,  170,  170,  170,  170,  170,  170,  170,
      170,  170,  170,  170,  170,  170,  170,  170,  170,  170,
      170,  170,  164,  164,  164,  164,  164,  164,  173,  173,
      164,  164,  164,    0,  164,  164,  164,  164,  164,  164,
      164,  164,  164
    } ;

static yyconst flex_int16_t yy_nxt[488] =
    {   0,
        6,    7,    8,    7,    9,   10,   11,    6,    6,   12,
        6,   13,   14,   15,   16,   17,   18,   15,   19,   15,
       20,   21,   22,   23,   24,   15,   25,   15,   26,   27,
       28,   15,   15,   15,   15,   14,   15,   16,   17,   18,
       19,   15,   20,   21,   22,   23,   24,   15,   25,   15,
       26,   27,   28,   15,   15,   15,   15,    6,    7,    8,
        7,    9,   10,   11,    6,   29,   12,    6,   13,   30,
       31,   32,   33,   34,   31,   35,   31,   36,   37,   38,
       39,   40,   31,   41,   31,   42,   43,   44,   31,   31,
       31,   31,   30,   31,   32,   33,   34,   35,   31,   36,

       37,   38,   39,   40,   31,   41,   31,   42,   43,   44,
       31,   31,   31,   31,   47,   53,   47,   55,   58,   56,
       59,   49,   54,   57,   61,   62,   63,  161,   64,   67,
       72,   47,   68,   47,   60,   65,  158,   73,   53,   55,
       58,   69,   56,   59,   54,   57,   61,   62,   63,   66,
       64,   67,   77,   70,   79,   68,   60,   71,   65,   80,
       73,   74,   75,   69,   79,   79,   81,   79,   79,  103,
       79,   66,   79,   83,   77,   70,   82,   84,   86,   71,
       79,   79,   80,   74,   75,   85,   94,  107,   81,   79,
      106,   79,   87,   79,   88,  110,   83,   92,   82,   84,

       79,   86,   89,   90,   79,   91,   95,   85,   94,  107,
       79,   93,  111,  106,   87,   96,   88,  112,  110,   97,
       92,   99,   79,   98,   89,   90,  113,   91,  100,   95,
      101,  102,  108,   93,  111,  114,  115,   96,  116,  112,
      117,   97,  118,  109,  119,   98,  120,  121,  113,  122,
      123,  100,  101,  102,  108,  124,  125,  114,  126,  115,
      116,  127,  117,  128,  118,  109,  119,  129,  120,  121,
       79,  122,  123,   79,   79,  130,   79,  124,  125,   79,
      126,   79,   79,  127,   79,  134,  128,   79,  132,  129,
       79,  138,   79,  131,  139,   79,  135,   79,  130,  133,

      136,  137,   79,  140,   79,   99,   79,   79,  134,   79,
      132,  144,   79,  138,  143,  131,  141,  139,  135,  142,
      147,  133,  136,  137,  145,  140,  146,   79,   79,   79,
       79,   79,  153,  144,  152,  156,  143,  149,  141,  103,
       79,  142,  147,  148,  154,  151,  145,  155,  146,  150,
      157,  158,  162,  163,  159,  153,   79,  152,  156,  149,
      162,  163,   79,   79,   79,  148,  154,  151,   79,  155,
       79,  150,   79,  157,   45,   45,   45,   45,   45,   45,
       48,   79,   48,   48,   48,   48,   51,   79,   51,   51,
       51,   51,   52,   79,   52,   78,   78,   78,  104,  104,

       79,  104,  104,  104,  105,   79,  105,  160,   79,   79,
      160,  160,  160,   79,   79,   79,   79,   79,   79,   79,
       76,   72,   50,   79,   76,   50,  164,   46,   46,    5,
      164,  164,  164,  164,  164,  164,  164,  164,  164,  164,
      164,  164,  164,  164,  164,  164,  164,  164,  164,  164,
      164,  164,  164,  164,  164,  164,  164,  164,  164,  164,
      164,  164,  164,  164,  164,  164,  164,  164,  164,  164,
      164,  164,  164,  164,  164,  164,  164,  164,  164,  164,
      164,  164,  164,  164,  164,  164,  164
    } ;

static yyconst flex_int16_t yy_chk[488] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,

        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    7,   14,    7,   16,   18,   17,
       19,  167,   14,   17,   20,   21,   21,  160,   21,   23,
       26,   47,   24,   47,   19,   22,  157,   26,   14,   16,
       18,   24,   17,   19,   14,   17,   20,   21,   21,   22,
       21,   23,   29,   25,   30,   24,   19,   25,   22,   30,
       26,   27,   27,   24,   32,   39,   30,   33,   34,   44,
       44,   22,   35,   33,   29,   25,   32,   33,   35,   25,
       36,  152,   30,   27,   27,   34,   39,   54,   30,   37,
       53,   38,   35,  151,   36,   56,   33,   38,   32,   33,

       40,   35,   37,   37,   41,   37,   40,   34,   39,   54,
       43,   38,   57,   53,   35,   40,   36,   58,   56,   41,
       38,   42,   42,   41,   37,   37,   59,   37,   42,   40,
       43,   43,   55,   38,   57,   60,   61,   40,   62,   58,
       63,   41,   64,   55,   65,   41,   66,   67,   59,   68,
       69,   42,   43,   43,   55,   70,   71,   60,   73,   61,
       62,   74,   63,   75,   64,   55,   65,   77,   66,   67,
       80,   68,   69,   81,   84,   80,   82,   70,   71,   85,
       73,   83,   87,   74,   86,   83,   75,   89,   82,   77,
       88,   87,   90,   81,   88,   91,   84,   92,   80,   82,

       85,   86,   93,   89,   96,   99,   99,  150,   83,   95,
       82,   93,   94,   87,   92,   81,   90,   88,   84,   91,
       96,   82,   85,   86,   94,   89,   95,   97,   98,  100,
      101,  102,  129,   93,  102,  155,   92,   98,   90,  103,
      103,   91,   96,   97,  153,  101,   94,  154,   95,  100,
      156,  158,  161,  161,  158,  129,  149,  102,  155,   98,
      162,  162,  148,  147,  146,   97,  153,  101,  145,  154,
      144,  100,  143,  156,  165,  165,  165,  165,  165,  165,
      166,  142,  166,  166,  166,  166,  168,  141,  168,  168,
      168,  168,  169,  140,  169,  170,  170,  170,  171,  171,

      139,  171,  171,  171,  172,  138,  172,  173,  137,  136,
      173,  173,  173,  135,  134,  133,  132,  131,  130,   78,
       76,   72,   50,   31,   28,   12,    5,    4,    3,  164,
      164,  164,  164,  164,  164,  164,  164,  164,  164,  164,
      164,  164,  164,  164,  164,  164,  164,  164,  164,  164,
      164,  164,  164,  164,  164,  164,  164,  164,  164,  164,
      164,  164,  164,  164,  164,  164,  164,  164,  164,  164,
      164,  164,  164,  164,  164,  164,  164,  164,  164,  164,
      164,  164,  164,  164,  164,  164,  164
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[40] =
    {   0,
0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 
        };

extern int qasm_flex_debug;
int qasm_flex_debug = 0;

static yy_state_type *yy_state_buf=0, *yy_state_ptr=0;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = (yy_hold_char); /* undo effects of setting up qasmtext */ \
yy_cp = (yy_full_match); /* restore poss. backed-over text */ \
++(yy_lp); \
goto find_rule; \
}

#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *qasmtext;
#line 1 "qasm-scanner.l"
#line 2 "qasm-scanner.l"
/*
 *
 * Pseudo assembler para maquina virtual QCode
 * Haga lo que quiera con ella, pero no hay garantias
 * Silvio Quadri (c) 2009
 *
 * */
#include <stdio.h>
#include <qcode.h>
#include "qasm-parser.h"
#include "qasm.h"

/*
 * Estas definiciones son para mantener el 
 * stack de llamados de defines y todo eso
 */

#define MAX_INCLUDE_DEPTH 32
YY_BUFFER_STATE   include_stack[MAX_INCLUDE_DEPTH];
char*             include_strings[MAX_INCLUDE_DEPTH];
int               include_lineno[MAX_INCLUDE_DEPTH];
int               include_stack_ptr = 0;
void              include_file( char* filename );



#line 723 "qasm-scanner.c"

#define INITIAL 0
#define string 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int qasmwrap (void );
#else
extern int qasmwrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( qasmtext, qasmleng, 1, qasmout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( qasmin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( qasmin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, qasmin))==0 && ferror(qasmin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(qasmin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int qasmlex (void);

#define YY_DECL int qasmlex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after qasmtext and qasmleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( qasmleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(qasmtext[qasmleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 38 "qasm-scanner.l"



#line 884 "qasm-scanner.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

        /* Create the reject buffer large enough to save one state per allowed character. */
        if ( ! (yy_state_buf) )
            (yy_state_buf) = (yy_state_type *)qasmalloc(YY_STATE_BUF_SIZE  );
            if ( ! (yy_state_buf) )
                YY_FATAL_ERROR( "out of dynamic memory in qasmlex()" );

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! qasmin )
			qasmin = stdin;

		if ( ! qasmout )
			qasmout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			qasmensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				qasm_create_buffer(qasmin,YY_BUF_SIZE );
		}

		qasm_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of qasmtext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();

		(yy_state_ptr) = (yy_state_buf);
		*(yy_state_ptr)++ = yy_current_state;

yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 165 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*(yy_state_ptr)++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_current_state != 164 );

yy_find_action:
		yy_current_state = *--(yy_state_ptr);
		(yy_lp) = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( (yy_lp) && (yy_lp) < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[(yy_lp)];
					{
					(yy_full_match) = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--(yy_state_ptr);
			(yy_lp) = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < qasmleng; ++yyl )
				if ( qasmtext[yyl] == '\n' )
					   
    qasmlineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 41 "qasm-scanner.l"
{ qasmlval = (long)strdup(qasmtext); 
                  ((char*)(long)qasmlval)[qasmleng - 1] = 0;
                  return  TOK_LAB; 
                }
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 46 "qasm-scanner.l"
{ 
                  char* s;
                  s = strchr( qasmtext, '"' );
                  if( s ){
                     char* filename = strdup( s + 1 );
                     char* pos_comillas = strchr( filename, '"' );
                     if( pos_comillas ){
                        pos_comillas[0]  = 0;
                        include_file( filename );
                     }
                  }
                }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 59 "qasm-scanner.l"
{ qasmlval = QCNOP; return TOK_INS; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 60 "qasm-scanner.l"
{ qasmlval = QCSTO; return TOK_INS; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 61 "qasm-scanner.l"
{ qasmlval = QCADD; return TOK_INS; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 62 "qasm-scanner.l"
{ qasmlval = QCSUB; return TOK_INS; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 63 "qasm-scanner.l"
{ qasmlval = QCINC; return TOK_INS; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 64 "qasm-scanner.l"
{ qasmlval = QCDEC; return TOK_INS; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 65 "qasm-scanner.l"
{ qasmlval = QCMUL; return TOK_INS; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 66 "qasm-scanner.l"
{ qasmlval = QCDIV; return TOK_INS; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 67 "qasm-scanner.l"
{ qasmlval = QCEQU; return TOK_INS; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 68 "qasm-scanner.l"
{ qasmlval = QCNEQ; return TOK_INS; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 69 "qasm-scanner.l"
{ qasmlval = QCLTH; return TOK_INS; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 70 "qasm-scanner.l"
{ qasmlval = QCLEQ; return TOK_INS; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 71 "qasm-scanner.l"
{ qasmlval = QCGTH; return TOK_INS; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 72 "qasm-scanner.l"
{ qasmlval = QCGEQ; return TOK_INS; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 73 "qasm-scanner.l"
{ qasmlval = QCPSH; return TOK_INS; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 74 "qasm-scanner.l"
{ qasmlval = QCPOP; return TOK_INS; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 75 "qasm-scanner.l"
{ qasmlval = QCJMP; return TOK_INS; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 76 "qasm-scanner.l"
{ qasmlval = QCJPZ; return TOK_INS; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 77 "qasm-scanner.l"
{ qasmlval = QCJNZ; return TOK_INS; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 78 "qasm-scanner.l"
{ qasmlval = QCCLL; return TOK_INS; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 79 "qasm-scanner.l"
{ qasmlval = QCALT; return TOK_INS; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 80 "qasm-scanner.l"
{ qasmlval = QCCLX; return TOK_INS; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 81 "qasm-scanner.l"
{ qasmlval = QCRET; return TOK_INS; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 83 "qasm-scanner.l"
{ int i = atoi( qasmtext + 1 );
                  if( i > 256 - 16 ) REJECT;
                  qasmlval = i + 16;
                  return  TOK_TMP;
                }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 89 "qasm-scanner.l"
{ int i = atoi( qasmtext + 1 );
                  if( i > 16 ) REJECT;
                  qasmlval = i; 
                  return  TOK_REG;
                }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 95 "qasm-scanner.l"
{ qasmlval = atoi( qasmtext ); 
                  return  TOK_NUM;
                }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 99 "qasm-scanner.l"
{ qasmlval = (long)strdup(qasmtext + 1); 
                  return  TOK_PTR; 
                }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 103 "qasm-scanner.l"
{ qasmlval = (long)strdup(qasmtext); 
                  return  TOK_WRD; 
                }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 107 "qasm-scanner.l"
{ BEGIN(string); }
	YY_BREAK
case 32:
/* rule 32 can match eol */
YY_RULE_SETUP
#line 108 "qasm-scanner.l"
{ qasmlval = (long)strdup(qasmtext); 
                  return TOK_STR;
                }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 111 "qasm-scanner.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 113 "qasm-scanner.l"
/* ignore whitespace */
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 114 "qasm-scanner.l"
/* ignora comentario */
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 115 "qasm-scanner.l"
/* ignora comentario */
	YY_BREAK
case 37:
/* rule 37 can match eol */
YY_RULE_SETUP
#line 116 "qasm-scanner.l"
{ return  TOK_SEP; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 117 "qasm-scanner.l"
{ return (int) qasmtext[0]; }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(string):
#line 119 "qasm-scanner.l"
{
                  if( include_stack_ptr == 0 ) yyterminate(); 
                  else {
                    if( include_strings[include_stack_ptr] ){
                      free( include_strings[include_stack_ptr] );
                      include_strings[include_stack_ptr] = NULL;
                    }
                    include_stack_ptr --;
                    YY_BUFFER_STATE b = YY_CURRENT_BUFFER;
                    qasm_switch_to_buffer(include_stack[include_stack_ptr] );
                    qasmlineno = include_lineno[include_stack_ptr];
                    qasm_delete_buffer(b );
                  } 
                }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 134 "qasm-scanner.l"
ECHO;
	YY_BREAK
#line 1233 "qasm-scanner.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed qasmin at a new source and called
			 * qasmlex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = qasmin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( qasmwrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * qasmtext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of qasmlex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			qasmrestart(qasmin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) qasmrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	(yy_state_ptr) = (yy_state_buf);
	*(yy_state_ptr)++ = yy_current_state;

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 165 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*(yy_state_ptr)++ = yy_current_state;
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    
	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 165 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 164);
	if ( ! yy_is_jam )
		*(yy_state_ptr)++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up qasmtext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --qasmlineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					qasmrestart(qasmin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( qasmwrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve qasmtext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');
	if ( YY_CURRENT_BUFFER_LVALUE->yy_at_bol )
		   
    qasmlineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void qasmrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        qasmensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            qasm_create_buffer(qasmin,YY_BUF_SIZE );
	}

	qasm_init_buffer(YY_CURRENT_BUFFER,input_file );
	qasm_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void qasm_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		qasmpop_buffer_state();
	 *		qasmpush_buffer_state(new_buffer);
     */
	qasmensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	qasm_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (qasmwrap()) processing, but the only time this flag
	 * is looked at is after qasmwrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void qasm_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	qasmin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE qasm_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) qasmalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in qasm_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) qasmalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in qasm_create_buffer()" );

	b->yy_is_our_buffer = 1;

	qasm_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with qasm_create_buffer()
 * 
 */
    void qasm_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		qasmfree((void *) b->yy_ch_buf  );

	qasmfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a qasmrestart() or at EOF.
 */
    static void qasm_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	qasm_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then qasm_init_buffer was _probably_
     * called from qasmrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void qasm_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		qasm_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void qasmpush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	qasmensure_buffer_stack();

	/* This block is copied from qasm_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from qasm_switch_to_buffer. */
	qasm_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void qasmpop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	qasm_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		qasm_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void qasmensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)qasmalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in qasmensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)qasmrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in qasmensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE qasm_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) qasmalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in qasm_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	qasm_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to qasmlex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       qasm_scan_bytes() instead.
 */
YY_BUFFER_STATE qasm_scan_string (yyconst char * yystr )
{
    
	return qasm_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to qasmlex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE qasm_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) qasmalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in qasm_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = qasm_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in qasm_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up qasmtext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		qasmtext[qasmleng] = (yy_hold_char); \
		(yy_c_buf_p) = qasmtext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		qasmleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int qasmget_lineno  (void)
{
        
    return qasmlineno;
}

/** Get the input stream.
 * 
 */
FILE *qasmget_in  (void)
{
        return qasmin;
}

/** Get the output stream.
 * 
 */
FILE *qasmget_out  (void)
{
        return qasmout;
}

/** Get the length of the current token.
 * 
 */
int qasmget_leng  (void)
{
        return qasmleng;
}

/** Get the current token.
 * 
 */

char *qasmget_text  (void)
{
        return qasmtext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void qasmset_lineno (int  line_number )
{
    
    qasmlineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see qasm_switch_to_buffer
 */
void qasmset_in (FILE *  in_str )
{
        qasmin = in_str ;
}

void qasmset_out (FILE *  out_str )
{
        qasmout = out_str ;
}

int qasmget_debug  (void)
{
        return qasm_flex_debug;
}

void qasmset_debug (int  bdebug )
{
        qasm_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from qasmlex_destroy(), so don't allocate here.
     */

    /* We do not touch qasmlineno unless the option is enabled. */
    qasmlineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_state_buf) = 0;
    (yy_state_ptr) = 0;
    (yy_full_match) = 0;
    (yy_lp) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    qasmin = stdin;
    qasmout = stdout;
#else
    qasmin = (FILE *) 0;
    qasmout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * qasmlex_init()
     */
    return 0;
}

/* qasmlex_destroy is for both reentrant and non-reentrant scanners. */
int qasmlex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		qasm_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		qasmpop_buffer_state();
	}

	/* Destroy the stack itself. */
	qasmfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    qasmfree ( (yy_state_buf) );
    (yy_state_buf)  = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * qasmlex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *qasmalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *qasmrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void qasmfree (void * ptr )
{
	free( (char *) ptr );	/* see qasmrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 134 "qasm-scanner.l"



void   qasm_scan_save( ){
  include_stack[include_stack_ptr]   = YY_CURRENT_BUFFER;
  if( qasm_filename )
    include_strings[include_stack_ptr] = strdup( qasm_filename );
  else
    include_strings[include_stack_ptr] = NULL;
  include_lineno[include_stack_ptr]  = qasmlineno;
  include_stack_ptr ++;
}


void   include_file( char* filename ){
  FILE* ff;
  // Listo ... verifico si hay lugar en el stack
  if( include_stack_ptr == MAX_INCLUDE_DEPTH ){
    qasmerror( "Insuficiente espacio para seguir incluyendo archivos" );
    return;
  }

  ff = fopen( filename, "r" );
  if( !ff ){
    char err[1024];
    if( strlen( filename ) > 128 ) filename[100] = '.';
    sprintf( err, "Error %d (%s) al abrir \"%s\"\n", errno, strerror( errno ), filename );
    qasmerror(err)  ;
    return;
  }


  qasmprintf( "Incluyendo : %s", filename );
  qasm_scan_save( );
  qasm_switch_to_buffer(qasm_create_buffer(ff,YY_BUF_SIZE ) );
  qasm_filename = filename;
  qasmlineno = 1;
  
}

  



